const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,p,dirty=false,editVersion=0,tab='PvP',opening='',mapHash='',selectedBase=0,terrainInputs={},lastResult=null;
const names={overview:'작업실',opening:'오프닝 빌드',settings:'운영과 컨트롤',rules:'조건과 판단',maps:'맵 지형',replays:'고수 리플레이',review:'검사와 반영'};
async function api(path,body){let r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});let d=await r.json();if(!r.ok)throw Error(d.error||'요청 실패');return d;}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6000);}
function edit(){editVersion++;dirty=true;$('#dirty').textContent='저장 전 변경';$('#dirty').className='pill amber';}
const readOnly=()=>p.id==='baseline';
function opt(value,label,chosen){return `<option value="${esc(value)}" ${value===chosen?'selected':''}>${esc(label)}</option>`;}
function intro(k,title,desc){return `<div class="intro"><div class="eyebrow">${k}</div><h1>${title}</h1><p>${desc}</p></div>`;}
function note(){return readOnly()?'<div class="note">순정 기준본입니다. 왼쪽의 <b>복사본 만들기</b>를 눌러 나만의 NNB를 편집하세요.</div>':!p.enabled?'<div class="note warning">현재 프로필은 꺼져 있습니다. 편집 내용은 저장되지만, 판단 미리보기와 실행본에 적용하려면 <a href="#review">검사와 반영</a>에서 프로필 사용을 켜세요.</div>':'';}
const options=sel=>Object.entries(p.config.Strategy.Strategies).filter(([k,b])=>b.Race==='Protoss').map(([k])=>opt(k,k,sel)).join('');
function route(){let key=location.hash.slice(1)||'overview';if(!names[key])key='overview';$('#crumb').textContent=names[key];$('#nav').querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.hash==='#'+key));$('#save').disabled=readOnly();$('#main').innerHTML=views[key]();if(key==='maps')drawMap();if(key==='safety'||key==='review')loadSafety();if(key==='review')loadHistory();$('#stage').textContent=readOnly()||!p.enabled?'순정 실행본 만들기':'오프라인 시험본 만들기';}
async function refresh(id){editVersion++;state=await api('/api/state');p=structuredClone(state.profiles.find(x=>x.id===id)||state.profiles[0]);dirty=false;$('#dirty').textContent='저장됨';$('#dirty').className='pill';$('#profile').innerHTML=state.profiles.map(x=>opt(x.id,x.name,p.id)).join('');mapHash ||=state.catalog.maps[0].hash;route();}
const views={
overview(){return intro('NEW NIMDAL BOT','더 좋은 판단을 만드는 작업실','순정의 동작을 기준으로 두고, 바꾸려는 행동과 연결된 부분을 함께 확인하세요. 무엇을 보고 어떻게 움직일지, 내 언어로 구체적으로 정할 수 있습니다.')+`<section class="box hero"><div><span class="pill">${readOnly()?'보존된 순정 기준본':'나의 실험 프로필'}</span><h2 style="margin-top:18px">${esc(p.name)}</h2><p>오프닝 → 정찰 정보 → 상황 판단 → 운영과 컨트롤.<br>설정의 연결을 이해하고, 고수의 실제 장면으로 확인하세요.</p><button class="primary" data-go="opening">오프닝부터 살펴보기 →</button></div><div class="stamp"><span class="small muted">2500+로 수집한 고수 자료</span><div class="number">${state.cohort.totalReplays.toLocaleString()}<span style="font-size:16px;letter-spacing:0"> 경기</span></div><span class="small muted">MMR 재검증 없이 기존 수집 기준 사용</span></div></section>${note()}<div class="grid three"><section class="box"><span class="eyebrow">01 · BASELINE</span><h2 style="margin-top:12px">순정과 나의 버전</h2><p class="small">순정 DLL·설정은 보존합니다. 복사본을 저장하고 새 실행 폴더로 내보냅니다.</p><button data-act="clone">복사본 만들기</button></section><section class="box"><span class="eyebrow">02 · DECISIONS</span><h2 style="margin-top:12px">상황별 행동</h2><p class="small">질럿 3기가 완성되면 출발. 이후에는 모으지 않고 합류. 조건을 직접 조합하세요.</p><button data-go="rules">판단 규칙 열기</button></section><section class="box"><span class="eyebrow">03 · TERRAIN</span><h2 style="margin-top:12px">현재 시즌 ${state.terrain.length}개 맵</h2><p class="small">본진과 확장, 길목과 지상 거리를 확인합니다. 캐시 검사 통과 ${state.terrain.filter(x=>x.ready).length} / ${state.terrain.length}.</p><button data-go="maps">지형 살펴보기</button></section></div><section class="box" style="margin-top:18px"><h2>이 에디터가 바꾸는 부분</h2><div class="diagram"><span>빌드 생산 순서</span><b>→</b><span>관측한 정보와 조건</span><b>→</b><span>운영·교전 기준 조정</span><b>→</b><span>순정 생산·전투 실행</span></div><p class="small">조건 규칙은 순정 판단의 지정된 부분을 조정합니다. 자원·건설 위치·긴급 방어·개별 마이크로가 함께 작동하므로, 설정 저장만으로 의도한 플레이가 검증된 것은 아닙니다.</p></section>`;},
opening(){let m=p.matchups[tab];if(!opening||!p.config.Strategy.Strategies[opening])opening=m.opening;let b=p.config.Strategy.Strategies[opening];return intro('OPENING LIBRARY','첫 일꾼부터, 빌드의 끝까지','종족전별 오프닝을 선택하고 생산 순서와 정찰·공격 명령을 편집합니다. 인구수는 명령 이름이 아니라 실제 생산 순서와 자원에 따라 결정됩니다.')+note()+`<div class="tabs">${['PvP','PvT','PvZ'].map(t=>`<button data-matchup="${t}" class="${tab===t?'active':''}">${t}</button>`).join('')}</div><section class="box"><div class="row between"><div><h2>${tab} 오프닝 선택</h2><label><input type="checkbox" id="fixed" ${m.fixed?'checked':''} ${readOnly()?'disabled':''}> 이 종족전은 선택한 빌드만 사용</label><p class="small">고정하면 상대 학습·맵별 오프닝 선택보다 우선합니다. 고정하지 않은 종족전은 순정 선택을 따릅니다.</p></div><select id="chosen-opening" aria-label="종족전 사용 빌드" ${readOnly()?'disabled':''}>${options(m.opening)}</select></div></section><section class="box"><div class="row between"><div><label for="build-select">살펴볼 빌드</label><select id="build-select">${options(opening)}</select></div><button data-act="copy-build" ${readOnly()?'disabled':''}>이 빌드를 복사</button></div><label for="group">오프닝 이후 운영 계열</label><select id="group" ${readOnly()?'disabled':''}>${[['zealots','질럿 압박'],['dragoons','드라군 중심'],['dark templar','다크 템플러'],['carriers','캐리어'],['drop','드롭']].map(([v,l])=>opt(v,l,b.OpeningGroup)).join('')}</select><div class="note">위에서 아래로 실행합니다. “@ natural”은 앞마당, “go scout”는 정찰입니다. “go aggressive at”의 숫자는 병력 수가 아닌 <b>게임 프레임</b>입니다. 병력 수로 출발하려면 조건과 판단에서 규칙을 만드세요.</div>${easyBuildControls()}<div id="steps" class="${readOnly()?'readonly':''}">${b.OpeningBuildOrder.map((s,i)=>`<div class="step"><span class="num">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(translate(s))}</strong><input aria-label="${i+1}번째 생산 항목" list="build-items" data-step="${i}" value="${esc(s)}"></div><div class="row"><button data-step-up="${i}" aria-label="${i+1}번째 항목 위로">↑</button><button data-step-down="${i}" aria-label="${i+1}번째 항목 아래로">↓</button><button data-step-delete="${i}" aria-label="${i+1}번째 항목 삭제">×</button></div></div>`).join('')}</div><datalist id="build-items">${state.catalog.buildItems.map(x=>`<option value="${esc(x)}">${esc(translate(x))}</option>`).join('')}</datalist><button data-act="add-step" class="secondary" style="margin-top:16px" ${readOnly()?'disabled':''}>+ 생산 / 행동 추가</button></section>`;},
settings(){return intro('OPERATIONS & MICRO','어떤 운영을 할지 정하세요','경제·정찰·교전의 실제 설정입니다. 종족 이름은 상대가 아닌 내 종족입니다. NNB의 프로토스 플레이에는 Protoss 값이 적용됩니다. 상대별 조정은 조건과 판단에서 만드세요.')+note()+['Macro','Micro','Strategy'].map(s=>`<section class="box"><h2>${{Macro:'경제와 생산',Micro:'교전과 유닛 생존',Strategy:'정찰과 상대 판단'}[s]}</h2>${state.catalog.fields.filter(f=>f.section===s).map(f=>{let value=p.config[s][f.key],entries=typeof value==='object'?Object.entries(value):[['공통',value]];return `<div class="settings-row"><div><h3>${esc(f.label)}</h3><span class="muted small">${esc(f.hint)}</span></div><div class="values">${entries.map(([race,v])=>`<label>${esc(race)}<br><input data-setting="${s}|${f.key}|${race}" aria-label="${esc(f.label+' '+race)}" type="${f.type==='bool'?'checkbox':'number'}" ${f.type==='bool'?(v?'checked':''):`value="${v}" min="${f.min}" max="${f.max}" step="${f.type==='float'?'.1':'1'}"`} ${readOnly()?'disabled':''}></label>`).join('')}</div></div>`;}).join('')}</section>`).join('');},
rules(){return intro('IF THIS, THEN THAT','보고, 판단하고, 움직이기','조건을 모두 만족하면 행동을 적용합니다. 같은 행동이 충돌하면 위쪽 규칙이 우선합니다. 겹치는 지시는 연결 검사에서 우선 관계를 명시해야 시험본을 만들 수 있습니다. 상대 정보는 현재 보이는 유닛과 순정 정찰 기억만 사용합니다.')+note()+`<div class="row" style="margin-bottom:20px"><button data-act="add-rule" class="primary" ${readOnly()?'disabled':''}>+ 새 판단 만들기</button><button data-act="zealot-preset" class="secondary" ${readOnly()?'disabled':''}>PvP 3질럿 출발 예시 추가</button></div><div class="note">“조건을 만족하는 동안”은 조건이 풀리면 원래 기준으로 돌아갑니다. “한 번 충족하면 유지”는 병력을 잃어도 다시 모으러 돌아가지 않습니다. 개별 유닛의 후퇴·긴급 방어는 계속 적용됩니다.</div><p class="small">현재는 목록에 있는 행동 기준을 수정할 수 있습니다. 미네랄 사이에 숨기기·특정 해처리 지정 타격·개별 유닛 좌표 이동 같은 새 컨트롤은 별도 구현이 필요합니다.</p>${p.rules.length?p.rules.map((r,i)=>ruleHTML(r,i)).join(''):'<div class="empty">아직 추가한 판단이 없습니다.<br>순정의 판단으로 운영합니다.</div>'}<section class="box"><h2>이 상황이면 무엇을 할까?</h2><p class="small">게임에서 사용하는 동일한 C++ 규칙 엔진으로 판단을 미리 확인합니다. 전투나 생산을 실행하는 시뮬레이션은 아닙니다.</p><div class="row"><label>종족전<br><select id="preview-match">${['PvP','PvT','PvZ'].map(v=>opt(v,v,tab)).join('')}</select></label><label>게임 시간(초)<br><input id="preview-seconds" type="number" value="180"></label><label>완성 질럿 수<br><input id="preview-zealots" type="number" value="3"></label><label>일꾼 수<br><input id="preview-workers" type="number" value="18"></label><label>기지 수<br><input id="preview-bases" type="number" value="1"></label><button data-act="preview" ${readOnly()?'disabled':''}>판단 확인</button></div><label for="extra-facts">추가 판단 정보 (선택, JSON)</label><textarea id="extra-facts" placeholder='{"minerals":400,"gas":100,"enemyNearBase":300}'>{}</textarea><pre id="preview-output">아직 확인하지 않았습니다.</pre></section>`;},
maps(){let m=state.terrain.find(x=>x.hash===mapHash)||state.terrain[0],g=m.geometry;return intro('SEASON MAP ATLAS','지형을 이해하는 운영','실제 맵의 이동 가능 영역 위에 기지와 길목을 표시합니다. 기지를 클릭하면 그 위치에서 다른 기지까지의 지상 거리를 확인할 수 있습니다.')+`<div class="row" style="margin-bottom:18px"><select id="map-select" aria-label="지형 맵 선택">${state.terrain.map(m=>opt(m.hash,m.name,mapHash)).join('')}</select><span class="pill ${m.ready?'':'amber'}">${m.ready?'순정 캐시 로더 검사 통과':'지형 검사 필요'}</span></div><section class="box map-layout"><div><canvas id="map" width="768" height="768" class="map-canvas" aria-label="이동 가능 지형, 기지와 길목 지도"></canvas><p class="small" style="margin:12px 0 0">밝은 바닥: 이동 가능 · 노랑: 시작 기지 · 초록: 확장 · 파랑: 미네랄 · 주황 선: 길목</p></div><div class="map-facts"><h2>${esc(m.name)}</h2>${g?`<div class="row between"><span>기지</span><b>${g.bases.length}</b></div><div class="row between"><span>길목</span><b>${g.chokes.length}</b></div><div class="row between"><span>영역</span><b>${g.regions.length}</b></div><hr><h3 id="base-label">기지 선택</h3><div id="base-distances"></div>`:'<p>분석 결과를 검증 중입니다.</p>'}<div class="note warning">캐시 읽기·시작 좌표·지상 연결 검사입니다. 실제 경기에서 건설과 유닛 이동까지 검증했다는 뜻은 아닙니다.</div></div></section>`;},
replays(){return intro('EXPERT REPLAY LIBRARY','고수는 이 상황에서 어떻게 했을까?','2500+로 수집된 자료를 그대로 사용합니다. 같은 맵과 빌드를 먼저 맞추고, 실제 장면에서 이동·타이밍·정찰 정보와 대응을 비교하세요.')+`<section class="box"><div class="row"><label>맵<br><select id="case-map">${state.catalog.maps.map(m=>opt(m.hash,m.name,mapHash)).join('')}</select></label><label>종족전 / 빌드<br><select id="case-opening"><option value="pvz|NineGateExpand">PvZ · 9게이트 확장</option><option value="pvp|TwoGate3Zealot">PvP · 10/12 3질럿</option><option value="pvt|Nexus23">PvT · 23넥서스</option></select></label><label>게임 시간(초)<br><input id="case-seconds" type="number" value="180" min="0" max="480"></label><label>일꾼 수 (선택)<br><input id="case-workers" type="number" placeholder="비교할 수"></label><label>기지 수 (선택)<br><input id="case-bases" type="number" placeholder="비교할 수"></label><button data-act="cases" class="primary">비슷한 장면 찾기</button></div><div class="note">평가용 ${state.cohort.bySplit.holdout}경기는 개선 근거 검색에서 제외합니다. 기본 검색은 상태를 교차 확인한 첫 8분입니다. 일치하는 자료가 없으면 다른 맵을 섞지 않습니다.</div><div id="cases"></div></section>`;},
review(){let original=state.profiles[0],changes=[];for(let f of state.catalog.fields){let a=original.config[f.section][f.key],b=p.config[f.section][f.key];if(JSON.stringify(a)!==JSON.stringify(b))changes.push([f.label,JSON.stringify(a),JSON.stringify(b)]);}for(let m of ['PvP','PvT','PvZ'])if(p.matchups[m].fixed)changes.push([m+' 오프닝','순정 선택',p.matchups[m].opening]);for(let [k,b]of Object.entries(p.config.Strategy.Strategies))if(JSON.stringify(b)!==JSON.stringify(original.config.Strategy.Strategies[k]))changes.push(['빌드 '+k,'순정 / 없음',b.OpeningBuildOrder.length+'개 순서']);return intro('REVIEW & STAGE','변경을 확인하고, 실행본 만들기','저장 → 연결 영향 검사 → 판단 확인 → 오프라인 시험본 생성. 각 실행본은 DLL·설정·맵 캐시와 해시를 별도 폴더에 보관합니다.')+`<section class="box"><label for="profile-name">프로필 이름</label><input id="profile-name" type="text" value="${esc(p.name)}" ${readOnly()?'disabled':''}><label><input id="profile-enabled" type="checkbox" ${p.enabled?'checked':''} ${readOnly()?'disabled':''}> 나의 프로필 사용 (끄면 순정 DLL·설정으로 실행본 생성)</label><div class="note">게임이나 래더를 자동으로 실행하지 않습니다. 현재 켜진 게임과 재생 중인 리플레이도 유지합니다.</div></section><section class="box"><h2>순정과 달라지는 점</h2><table><thead><tr><th>항목</th><th>순정</th><th>나의 설정</th></tr></thead><tbody>${changes.map(r=>`<tr>${r.map((x,i)=>`<td class="${i===2?'value-change':''}">${esc(x)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="3">기본 설정과 빌드 변경 없음</td></tr>'}<tr><td>추가 판단 규칙</td><td>없음</td><td>${p.rules.filter(r=>r.enabled).length}개 사용 / ${p.rules.length}개 저장</td></tr></tbody></table></section><section class="box"><div class="row between"><div><h2>적용 전 검사</h2><p class="small">지원하지 않는 행동, 범위를 벗어난 수치, 잘못된 생산 항목을 확인합니다.</p></div><button data-act="validate" ${readOnly()?'disabled':''}>설정 검사</button></div><pre id="validation">아직 검사하지 않았습니다.</pre></section><section class="box"><h2>최근 만든 실행본</h2><pre>${esc(state.lastStage?JSON.stringify(state.lastStage,null,2):'아직 실행본을 만들지 않았습니다.')}</pre><p class="small">실행본 생성은 게임 내 성능 검증과 구분됩니다. 다음 단계는 오프라인 게임에서 생산·정찰·전투가 함께 정상 작동하는지 확인하는 것입니다.</p></section>`;}
};
function easyBuildControls(){return `<div class="note"><b>쉬운 순서 추가</b><div class="row"><label>무엇을 할까요?<br><select id="easy-item">${Object.entries(state.catalog.units).filter(([id])=>+id>=60&&![68,103].includes(+id)).map(([id,u])=>opt(u.name,u.label,'Probe')).join('')}${[['go scout','정찰 보내기'],['go aggressive','공격 허용하기'],['go defensive','방어 유지하기'],['go start gas','가스 채취 시작'],['go stop gas','가스 채취 중단']].map(([k,v])=>opt(k,v,'')).join('')}</select></label><label>몇 개?<br><input id="easy-count" type="number" min="1" max="100" value="1"></label><label>건물을 지을 위치<br><select id="easy-location">${[['','자동'],['main','본진'],['natural','앞마당'],['expo','확장'],['hidden','숨겨진 위치'],['proxy','전진 위치']].map(([k,v])=>opt(k,v,'')).join('')}</select></label><button data-act="easy-add" ${readOnly()?'disabled':''}>이 순서 추가</button></div><span class="small">명령은 한 번 실행합니다. 위치 선택은 건물에만 적용합니다. 아래에서 ↑ ↓로 순서를 바꿀 수 있습니다.</span></div>`;}
function translate(s){let result=s;for(let u of Object.values(state.catalog.units).sort((a,b)=>b.name.length-a.name.length)){result=result.replace(new RegExp(u.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),u.label);}const commands={'go aggressive':'공격 허용','go defensive':'방어 유지','go scout':'정찰 출발','go start gas':'가스 채취 시작','go stop gas':'가스 채취 중단'};for(let[k,v]of Object.entries(commands))result=result.replace(k,v);return result.replaceAll(' @ natural',' · 앞마당').replaceAll(' then ',' → ');}
function factsOptions(sel){return Object.entries(state.catalog.facts).map(([k,v])=>opt(k,v,sel)).join('')+Object.entries(state.catalog.units).map(([id,u])=>opt('own_'+id,'우리 '+u.label+' 완성 수',sel)+opt('visible_'+id,'지금 보이는 '+u.label+' 수',sel)).join('');}
function ruleHTML(r,i){return `<section class="box rule"><div class="rule-top"><div class="row"><span class="pill">우선순위 ${i+1}</span><label><input type="checkbox" data-rule-on="${i}" ${r.enabled?'checked':''} ${readOnly()?'disabled':''}> 사용</label></div><div class="row"><button data-rule-up="${i}" aria-label="규칙 위로">↑</button><button data-rule-down="${i}" aria-label="규칙 아래로">↓</button><button class="danger" data-rule-delete="${i}">삭제</button></div></div><input class="rule-title" aria-label="규칙 이름" data-rule-name="${i}" value="${esc(r.name||'새 판단')}"><div class="scope"><label>종족전<br><select data-rule-prop="${i}|matchup">${['','PvP','PvT','PvZ'].map(v=>opt(v,v||'모든 종족전',r.matchup)).join('')}</select></label><label>맵<br><select data-rule-prop="${i}|map">${opt('','모든 맵',r.map)+state.catalog.maps.map(m=>opt(m.hash,m.name,r.map)).join('')}</select></label><label>빌드<br><select data-rule-prop="${i}|opening">${opt('','모든 빌드',r.opening)+options(r.opening)}</select></label><label>유지 방식<br><select data-rule-prop="${i}|mode">${opt('while','조건을 만족하는 동안',r.mode)+opt('once','한 번 충족하면 경기 내내',r.mode)}</select></label></div><div class="rule-flow"><div><label>이 조건을 모두 만족하면</label>${r.conditions.map((c,j)=>`<div class="condition"><select aria-label="판단 정보" data-cond="${i}|${j}|field">${factsOptions(c.field)}</select><select aria-label="비교" data-cond="${i}|${j}|op">${['>=','<=','==','>','<'].map(o=>opt(o,({'>=':'이상','<=':'이하','==':'같음','>':'초과','<':'미만'})[o],c.op)).join('')}</select><input aria-label="기준값" type="number" data-cond="${i}|${j}|value" value="${c.value}"><button data-cond-del="${i}|${j}" aria-label="조건 삭제">×</button></div>`).join('')}<button class="secondary" data-cond-add="${i}">+ 조건</button></div><span class="arrow">→</span><div><label>이렇게 판단하기</label>${Object.entries(r.actions).map(([k,v])=>`<div class="condition"><select aria-label="행동" data-action-key="${i}|${k}">${Object.entries(state.catalog.actions).map(([key,a])=>opt(key,a.label,k)).join('')}</select><input aria-label="행동 값" type="number" data-action-val="${i}|${k}" value="${v}" min="${state.catalog.actions[k].min}" max="${state.catalog.actions[k].max}"><button data-action-del="${i}|${k}" aria-label="행동 삭제">×</button></div><p class="small">${esc(state.catalog.actions[k].hint)}</p>`).join('')}<button class="secondary" data-action-add="${i}">+ 행동</button></div></div><label>근거와 고려할 점</label><textarea data-rule-note="${i}" placeholder="참고 리플레이, 시간, 당시 확인한 적 정보, 이 행동을 멈춰야 하는 상황">${esc(r.note||'')}</textarea></section>`;}
function newRule(){return {id:'rule-'+crypto.randomUUID().slice(0,8),name:'새 판단',enabled:false,matchup:tab,map:'',opening:'',mode:'while',conditions:[{field:'seconds',op:'>=',value:0}],actions:{retreatScore:0},note:''};}
async function save(){if(readOnly())return;p=await api('/api/save',{profile:p});await refresh(p.id);toast('저장했습니다. 실행 중인 게임에는 변경하지 않았습니다.');}
async function stage(){if(dirty)await save();const check=await api('/api/safety',{profile:p});if(check.blocked){location.hash='safety';route();return toast('연결 문제를 해결한 뒤 시험본을 만들 수 있습니다. 초안은 저장했습니다.');}state.lastStage=await api('/api/stage',{id:p.id});location.hash='review';route();toast('별도 실행본을 만들었습니다. 게임은 실행하지 않았습니다.');}
$('#save').onclick=()=>save().catch(e=>toast(e.message));$('#stage').onclick=()=>stage().catch(e=>toast(e.message));
async function doClone(){if(dirty)throw Error('복사 전에 현재 변경을 저장하세요.');let n=await api('/api/clone',{id:p.id});await refresh(n.id);toast('편집할 복사본을 만들었습니다.');}
$('#clone').onclick=()=>doClone().catch(e=>toast(e.message));$('#profile').onchange=e=>{if(dirty){e.target.value=p.id;return toast('프로필을 바꾸기 전에 변경을 저장하세요.');}refresh(e.target.value).catch(e=>toast(e.message));};
window.onhashchange=route;window.onbeforeunload=e=>{if(dirty){e.preventDefault();e.returnValue='';}};
document.addEventListener('change',e=>{let t=e.target,d=t.dataset;try{
 if(t.id==='build-select'){opening=t.value;return route();}if(t.id==='map-select'){mapHash=t.value;selectedBase=0;return route();}
 if(readOnly())return;
 if(t.id==='fixed')p.matchups[tab].fixed=t.checked;
 else if(t.id==='chosen-opening'){p.matchups[tab].opening=t.value;opening=t.value;edit();return route();}
 else if(t.id==='group')p.config.Strategy.Strategies[opening].OpeningGroup=t.value;
 else if(t.id==='profile-name')p.name=t.value;
 else if(t.id==='profile-enabled')p.enabled=t.checked;
 else if(d.step!==undefined)p.config.Strategy.Strategies[opening].OpeningBuildOrder[+d.step]=t.value;
 else if(d.setting){let[s,k,r]=d.setting.split('|'),v=t.type==='checkbox'?t.checked:Number(t.value);if(r==='공통')p.config[s][k]=v;else p.config[s][k][r]=v;}
 else if(d.ruleOn!==undefined)p.rules[+d.ruleOn].enabled=t.checked;
 else if(d.ruleName!==undefined)p.rules[+d.ruleName].name=t.value;
 else if(d.ruleNote!==undefined)p.rules[+d.ruleNote].note=t.value;
 else if(d.ruleProp){let[i,k]=d.ruleProp.split('|');p.rules[i][k]=t.value;}
 else if(d.cond){let[i,j,k]=d.cond.split('|');p.rules[i].conditions[j][k]=k==='value'?Number(t.value):t.value;}
 else if(d.actionVal){let[i,k]=d.actionVal.split('|');p.rules[i].actions[k]=Number(t.value);}
 else if(d.actionKey){let[i,k]=d.actionKey.split('|');delete p.rules[i].actions[k];p.rules[i].actions[t.value]=Math.max(0,state.catalog.actions[t.value].min);edit();return route();}
 else return;edit();
}catch(err){toast(err.message);}});
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;let d=b.dataset;try{
 if(d.go){location.hash=d.go;return;}if(d.matchup){tab=d.matchup;opening=p.matchups[tab].opening;return route();}
 if(d.act==='clone')return await doClone();
 if(d.act==='cases'){let[matchup,op]=$('#case-opening').value.split('|'),rows=await api('/api/cases?'+new URLSearchParams({map:$('#case-map').value,matchup,opening:op,frame:Math.floor(Number($('#case-seconds').value)*24),workers:$('#case-workers').value,bases:$('#case-bases').value}));$('#cases').innerHTML=rows.length?rows.map((r,i)=>`<div class="list-line"><h3>사례 ${i+1} · ${Math.floor(r.situation.frame/24)}초 · 일꾼 ${r.situation.workers} · 기지 ${r.situation.bases}</h3><p class="small">미네랄 ${r.situation.minerals} / 가스 ${r.situation.gas} · 우리 병력 가치 ${r.situation.armyValue} · 현재 보이는 적 ${r.situation.enemyVisibleValue}</p><details><summary>리플레이와 뒤이은 생산 관측</summary><pre>${esc(r.replay)}\n${esc(JSON.stringify(r.nextBuildObservations,null,2))}</pre></details></div>`).join(''):'<div class="empty">이 맵·빌드·시간에 맞는 검증 자료가 없습니다.</div>';return;}
 if(readOnly())return;
 if(d.act==='copy-build'){let name='NNB-'+tab+'-'+Date.now().toString().slice(-6);p.config.Strategy.Strategies[name]=structuredClone(p.config.Strategy.Strategies[opening]);opening=name;p.matchups[tab].opening=name;}
 else if(d.act==='easy-add'){let item=$('#easy-item').value,n=Number($('#easy-count').value),place=$('#easy-location').value;if(!Number.isInteger(n)||n<1||n>100)throw Error('개수는 1~100으로 입력하세요');let unit=Object.entries(state.catalog.units).find(([id,u])=>u.name===item);if(unit&&+unit[0]>=154&&place)item+=' @ '+place;if(unit&&n>1)item=n+' x '+item;p.config.Strategy.Strategies[opening].OpeningBuildOrder.push(item);}
 else if(d.act==='add-step')p.config.Strategy.Strategies[opening].OpeningBuildOrder.push('Probe');
 else if(d.stepUp!==undefined||d.stepDown!==undefined||d.stepDelete!==undefined){let a=p.config.Strategy.Strategies[opening].OpeningBuildOrder,i=Number(d.stepUp??d.stepDown??d.stepDelete);if(d.stepDelete!==undefined)a.splice(i,1);else{let j=i+(d.stepUp!==undefined?-1:1);if(j>=0&&j<a.length)[a[i],a[j]]=[a[j],a[i]];}}
 else if(d.act==='add-rule')p.rules.push(newRule());
 else if(d.act==='zealot-preset'){let launch=newRule();Object.assign(launch,{name:'3질럿 완성 후 출발, 후속 병력 합류',matchup:'PvP',opening:p.matchups.PvP.opening,mode:'once',conditions:[{field:'own_65',op:'>=',value:3}],actions:{aggression:1},note:'첫 3질럿이 완성되면 공격 허용을 유지합니다. 후속 5·7질럿을 다시 기다리지 않습니다. 실제 합류 경로·개별 후퇴는 순정 전투 코드가 정합니다.'});let wait=newRule();Object.assign(wait,{name:'첫 3질럿 전까지 방어',matchup:'PvP',opening:p.matchups.PvP.opening,conditions:[{field:'own_65',op:'<',value:3}],actions:{aggression:0}});p.rules.push(launch,wait);toast('예시 2개를 꺼진 상태로 추가했습니다. 적용할 빌드와 조건을 확인한 뒤 켜세요.');}
 else if(d.ruleDelete!==undefined){const removed=p.rules.splice(+d.ruleDelete,1)[0];for(const r of p.rules)r.overrides=(r.overrides||[]).filter(x=>x!==removed.id);}
 else if(d.ruleUp!==undefined||d.ruleDown!==undefined){let i=Number(d.ruleUp??d.ruleDown),j=i+(d.ruleUp!==undefined?-1:1);if(j>=0&&j<p.rules.length){[p.rules[i],p.rules[j]]=[p.rules[j],p.rules[i]];for(let k=0;k<p.rules.length;k++)p.rules[k].overrides=(p.rules[k].overrides||[]).filter(id=>p.rules.findIndex(x=>x.id===id)>k);}}
 else if(d.condAdd!==undefined)p.rules[+d.condAdd].conditions.push({field:'seconds',op:'>=',value:0});
 else if(d.condDel){let[i,j]=d.condDel.split('|');p.rules[i].conditions.splice(+j,1);}
 else if(d.actionAdd!==undefined){let a=p.rules[+d.actionAdd].actions,key=Object.keys(state.catalog.actions).find(k=>!(k in a));if(key)a[key]=Math.max(0,state.catalog.actions[key].min);}
 else if(d.actionDel){let[i,k]=d.actionDel.split('|');delete p.rules[i].actions[k];}
 else if(d.act==='validate'){let r=await api('/api/validate',{profile:p});$('#validation').textContent=r.note;return;}
 else if(d.act==='preview'){let facts=JSON.parse($('#extra-facts').value);Object.assign(facts,{seconds:+$('#preview-seconds').value,own_65:+$('#preview-zealots').value,workers:+$('#preview-workers').value,bases:+$('#preview-bases').value});let match=$('#preview-match').value;let r=await api('/api/preview',{profile:p,facts,matchup:match,map:mapHash,opening:p.matchups[match].opening});let resolved=Object.entries(r.actions).map(([k,v])=>state.catalog.actions[k].label+': '+v);$('#preview-output').textContent='충족 규칙: '+(r.matched.map(id=>p.rules.find(x=>x.id===id)?.name||id).join(', ')||'없음')+'\n'+(resolved.join('\n')||'추가 조정 없이 순정 판단 사용');return;}
 else return;edit();route();
}catch(err){toast(err.message);}});
async function drawMap(){let m=state.terrain.find(x=>x.hash===mapHash);if(!m)return;try{let data=terrainInputs[mapHash]||=await api('/api/terrain?hash='+mapHash);let canvas=$('#map');if(!canvas)return;let ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,sx=W/(data.width*32),sy=H/(data.height*32);ctx.fillStyle='#152f2c';ctx.fillRect(0,0,W,H);let raw=document.createElement('canvas');raw.width=data.width*4;raw.height=data.height*4;let rc=raw.getContext('2d'),im=rc.createImageData(raw.width,raw.height);for(let y=0;y<raw.height;y++)for(let x=0;x<raw.width;x++){let i=(y*raw.width+x)*4,v=data.walkRows[y][x]==='1';im.data.set(v?[73,100,79,255]:[21,47,44,255],i);}rc.putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(raw,0,0,W,H);if(m.geometry){ctx.strokeStyle='#87ac7860';ctx.lineWidth=1;for(let r of m.geometry.regions){ctx.beginPath();r.polygon.forEach(([x,y],i)=>i?ctx.lineTo(x*sx,y*sy):ctx.moveTo(x*sx,y*sy));ctx.closePath();ctx.stroke();}ctx.strokeStyle='#e1aa64';ctx.lineWidth=3;for(let c of m.geometry.chokes){ctx.beginPath();ctx.moveTo(c.sides[0][0]*sx,c.sides[0][1]*sy);ctx.lineTo(c.sides[1][0]*sx,c.sides[1][1]*sy);ctx.stroke();}}
for(let u of data.units){if([176,177,178,188].includes(u.type)){ctx.fillStyle=u.type===188?'#80cc9a':'#81bada';ctx.fillRect(u.x*sx-2,u.y*sy-2,5,4);}}
if(m.geometry){m.geometry.bases.forEach((b,i)=>{ctx.fillStyle=b.start?'#e6d791':'#a6cc9e';ctx.strokeStyle=i===selectedBase?'white':'#223d2a';ctx.lineWidth=i===selectedBase?3:1;ctx.beginPath();ctx.arc(b.x*sx,b.y*sy,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#173c30';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText(i+1,b.x*sx,b.y*sy+3);});let base=m.geometry.bases[selectedBase]||m.geometry.bases[0];$('#base-label').textContent='기지 '+(selectedBase+1)+(base.start?' · 시작 위치':' · 확장');$('#choke-detail')?.remove();let choke=m.geometry.chokes.map(c=>({...c,d:Math.hypot(c.x-base.x,c.y-base.y)})).sort((a,b)=>a.d-b.d)[0];$('#base-label').insertAdjacentHTML('afterend','<p id="choke-detail" class="small">가장 가까운 길목 폭 '+Math.round(choke.width)+' px · 직선 거리 '+Math.round(choke.d)+' px</p>');$('#base-distances').innerHTML=base.distances.map((v,i)=>({v,i})).filter(x=>x.i!==selectedBase).sort((a,b)=>a.v-b.v).map(x=>`<div class="row between small" style="margin:8px 0"><span>→ 기지 ${x.i+1}</span><b>${x.v<0?'연결 없음':Math.round(x.v)+' px'}</b></div>`).join('');canvas.onclick=e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*data.width*32,y=(e.clientY-r.top)/r.height*data.height*32;selectedBase=m.geometry.bases.map((b,i)=>({i,d:Math.hypot(x-b.x,y-b.y)})).sort((a,b)=>a.d-b.d)[0].i;drawMap();};}
}catch(e){toast(e.message);}}
window.addEventListener('DOMContentLoaded',()=>refresh('baseline').catch(e=>{$('#main').textContent='작업실을 열 수 없습니다: '+e.message;}));
