// Generated by tools/judgment_catalog.py. Defaults preserve pinned Locutus thresholds.
#pragma once
#include "rapidjson/document.h"
#include <map>
#include <string>
#include <stdexcept>
namespace NNB {
struct PlanSetting {int original,minimum,maximum;};
inline const std::map<std::string,PlanSetting>& planSpecs(){
    static const std::map<std::string,PlanSetting> fields={
        {"startFrame", {100,0,24000}},
        {"endFrame", {10000,100,43200}},
        {"proxyEnabled", {1,0,1}},
        {"workerEnabled", {1,0,1}},
        {"workerUntil", {3000,0,24000}},
        {"workerRadius", {1000,64,3000}},
        {"workerCount", {3,1,30}},
        {"fastEnabled", {1,0,1}},
        {"fastPool", {1600,0,12000}},
        {"fastLing", {3200,0,12000}},
        {"fastGateway", {1750,0,12000}},
        {"fastZealot", {3300,0,12000}},
        {"fastBarracks", {1400,0,12000}},
        {"fastMarine", {3000,0,12000}},
        {"notFastEnabled", {1,0,1}},
        {"notFastDrone", {6,0,60}},
        {"notFastSCV", {8,0,60}},
        {"notFastProbe", {9,0,60}},
        {"notFastAfter", {8000,0,43200}},
        {"heavyEnabled", {1,0,1}},
        {"heavyLingUntil", {5500,0,24000}},
        {"heavyLingCount", {10,0,100}},
        {"oneHatchAfter", {4000,0,24000}},
        {"oneHatchCount", {1,1,10}},
        {"oneHatchDrones", {9,0,60}},
        {"heavyHatchCount", {2,1,10}},
        {"heavyHatchLings", {5,0,100}},
        {"heavyBarracks", {2,1,10}},
        {"heavyCC", {1,0,10}},
        {"heavyMarines", {3,0,100}},
        {"heavyGateways", {2,1,10}},
        {"heavyNexus", {1,0,10}},
        {"heavyZealots", {3,0,100}},
        {"hydraEnabled", {1,0,1}},
        {"hydraUntil", {7000,0,24000}},
        {"hydraHatches", {2,1,10}},
        {"hydraLings", {3,0,100}},
        {"wallEnabled", {1,0,1}},
        {"wallUntil", {6000,0,24000}},
        {"darkEnabled", {1,0,1}},
        {"darkUntil", {10000,0,24000}},
        {"darkCount", {0,0,20}}
    };return fields;
}
class PlanSettings {
    std::map<std::string,int> values;
public:
    void load(const rapidjson::Value& v){
        std::map<std::string,int> pending;
        if(!v.IsObject())throw std::runtime_error("Invalid recognition settings");
        for(auto i=v.MemberBegin();i!=v.MemberEnd();++i){
            auto spec=planSpecs().find(i->name.GetString());
            if(spec==planSpecs().end()||!i->value.IsInt()||i->value.GetInt()<spec->second.minimum||i->value.GetInt()>spec->second.maximum)throw std::runtime_error("Invalid recognition threshold");
            pending[i->name.GetString()]=i->value.GetInt();
        }
        const int start=pending.count("startFrame")?pending.at("startFrame"):planSpecs().at("startFrame").original;
        const int end=pending.count("endFrame")?pending.at("endFrame"):planSpecs().at("endFrame").original;
        if(start>=end)throw std::runtime_error("Invalid recognition time window");
        values=std::move(pending);
    }
    int get(const char* key) const {auto i=values.find(key);return i==values.end()?planSpecs().at(key).original:i->second;}
};
}
