"""UI descriptions and bounded settings for existing OpponentPlan branches.

Defaults are the pinned Locutus values. Values change thresholds, never branch order.
"""
GROUPS = [
    ('window','추정하는 시간 범위','경기 초반에 12프레임마다 검사합니다. 확정된 판단은 다시 추정하지 않습니다.',[
        ('startFrame','추정을 시작할 시간 이후',100,0,24000,'frames'),('endFrame','추정을 끝낼 시간 이전',10000,100,43200,'frames')]),
    ('proxy','본진 안 전진 건물','정보 관리자가 우리 본진 안의 적 전진 건물을 확인하면 전진 건물 전략으로 확정합니다.',[]),
    ('worker','일꾼 러시','초반 제한 시간 안에, 우리 본진 중심 근처에서 현재 보이는 적 일꾼이 기준 이상이면 일꾼 러시로 봅니다. 이 판단은 바로 확정하지 않습니다.',[
        ('workerUntil','검사할 시간 이전',3000,0,24000,'frames'),('workerRadius','본진 중심과의 거리 미만 (픽셀)',1000,64,3000,'number'),('workerCount','보이는 적 일꾼 수 이상',3,1,30,'number')]),
    ('fast','아주 빠른 초반 공격','아래 항목 중 하나라도 기준 시각보다 이르게 확인되면 빠른 러시로 확정합니다. 정찰 정보로 추정한 시각입니다. 건물은 건설 시작, 저글링·질럿·마린은 이동 시간을 거꾸로 계산한 생산 완료 시각을 사용합니다.',[
        ('fastPool','스포닝 풀 추정 건설 시작 미만',1600,0,12000,'frames'),('fastLing','저글링 추정 생산 완료 미만',3200,0,12000,'frames'),('fastGateway','게이트웨이 추정 건설 시작 미만',1750,0,12000,'frames'),('fastZealot','질럿 추정 생산 완료 미만',3300,0,12000,'frames'),('fastBarracks','배럭 추정 건설 시작 미만',1400,0,12000,'frames'),('fastMarine','마린 추정 생산 완료 미만',3000,0,12000,'frames')]),
    ('notFast','초고속 러시가 아닌 것으로 추정','아직 판단하지 못했고 적 일꾼이 기준보다 많으면 초고속 러시가 아니라고 봅니다. 정보가 부족해도 안전장치 시간이 지나면 이 판단을 사용합니다. 다른 구체적 판단으로 바뀔 수 있습니다.',[
        ('notFastDrone','드론 수 초과',6,0,60,'number'),('notFastSCV','SCV 수 초과',8,0,60,'number'),('notFastProbe','프로브 수 초과',9,0,60,'number'),('notFastAfter','정보 부족 시 안전장치 시간 이후',8000,0,43200,'frames')]),
    ('heavy','초반 병력 집중 공격','아래 다섯 경로 중 하나가 맞으면 병력 집중 공격으로 확정합니다. “가스 건물 0”은 정찰로 아직 확인하지 못했다는 뜻일 수도 있습니다.',[
        ('heavyLingUntil','① 이 시간 이전',5500,0,24000,'frames'),('heavyLingCount','① 저글링 수 초과',10,0,100,'number'),
        ('oneHatchAfter','② 이 시간 이후',4000,0,24000,'frames'),('oneHatchCount','② 해처리 수 같음',1,1,10,'number'),('oneHatchDrones','② 드론 수 이하',9,0,60,'number'),
        ('heavyHatchCount','③ 해처리 수 이상',2,1,10,'number'),('heavyHatchLings','③ 저글링 수 초과 (풀 확인·익스트랙터 미확인)',5,0,100,'number'),
        ('heavyBarracks','④ 배럭 수 이상',2,1,10,'number'),('heavyCC','④ 커맨드 센터 수 이하 (리파이너리 미확인)',1,0,10,'number'),('heavyMarines','④ 마린 수 초과',3,0,100,'number'),
        ('heavyGateways','⑤ 게이트웨이 수 이상',2,1,10,'number'),('heavyNexus','⑤ 넥서스 수 이하 (어시밀레이터 미확인)',1,0,10,'number'),('heavyZealots','⑤ 질럿 수 초과',3,0,100,'number')]),
    ('hydra','히드라 공격 준비','제한 시간 안에 해처리와 히드라 덴이 확인되고 저글링이 적으면 히드라 공격 준비로 확정합니다. 실제 히드라를 이미 봤다는 뜻은 아닙니다.',[
        ('hydraUntil','검사할 시간 이전',7000,0,24000,'frames'),('hydraHatches','해처리 수 이상',2,1,10,'number'),('hydraLings','저글링 수 미만 (히드라 덴 확인)',3,0,100,'number')]),
    ('wall','테란 입구 막기','상대가 테란이고 정보 관리자가 입구 막기를 확인하면 확정합니다. 벽을 찾는 공간 계산 자체는 이 시간 설정으로 바뀌지 않습니다.',[
        ('wallUntil','검사할 시간 이전',6000,0,24000,'frames')]),
    ('dark','다크 템플러 오프닝','제한 시간 안에 다크 템플러를 확인하면 확정합니다. 아둔·템플러 아카이브만 보고 예측하는 조건은 아닙니다.',[
        ('darkUntil','검사할 시간 이전',10000,0,24000,'frames'),('darkCount','다크 템플러 수 초과',0,0,20,'number')]),
]
PLAN_FACTS={'plan_proxy':'현재 추정: 전진 건물 (1/0)','plan_worker':'현재 추정: 일꾼 러시 (1/0)','plan_fast':'현재 추정: 아주 빠른 러시 (1/0)','plan_notFast':'현재 추정: 초고속 러시 아님 (1/0)','plan_heavy':'현재 추정: 초반 병력 집중 (1/0)','plan_hydra':'현재 추정: 히드라 공격 준비 (1/0)','plan_wall':'현재 추정: 테란 입구 막기 (1/0)','plan_dark':'현재 추정: 다크 템플러 (1/0)'}


def catalog():
    return [dict(id=id,label=label,description=desc,fixed=id not in ('window','worker','notFast'),
                 fields=([dict(key=id+'Enabled',label='이 판단 사용',default=1,min=0,max=1,unit='bool')] if id!='window' else [])+
                        [dict(key=k,label=l,default=d,min=lo,max=hi,unit=u) for k,l,d,lo,hi,u in fields])
            for id,label,desc,fields in GROUPS]


def specs():return {f['key']:f for g in catalog() for f in g['fields']}


def validate(values):
    if not isinstance(values,dict):raise ValueError('전략 추정 설정이 잘못되었습니다')
    fields=specs()
    for key,value in values.items():
        if key not in fields or type(value) is not int or not fields[key]['min']<=value<=fields[key]['max']:
            raise ValueError('전략 추정 기준이 허용 범위를 벗어났습니다: '+str(key))
    start=values.get('startFrame',fields['startFrame']['default']);end=values.get('endFrame',fields['endFrame']['default'])
    if start>=end:raise ValueError('전략 추정 시작 시간은 종료 시간보다 빨라야 합니다')


def native_header():
    entries=',\n'.join('        {"%s", {%d,%d,%d}}'%(k,s['default'],s['min'],s['max']) for k,s in specs().items())
    return '''// Generated by tools/judgment_catalog.py. Defaults preserve pinned Locutus thresholds.
#pragma once
#include "rapidjson/document.h"
#include <map>
#include <string>
#include <stdexcept>
namespace NNB {
struct PlanSetting {int original,minimum,maximum;};
inline const std::map<std::string,PlanSetting>& planSpecs(){
    static const std::map<std::string,PlanSetting> fields={
'''+entries+'''
    };return fields;
}
class PlanSettings {
    std::map<std::string,int> values;
public:
    void load(const rapidjson::Value& v){
        std::map<std::string,int> pending;
        if(!v.IsObject())throw std::runtime_error("Invalid recognition settings");
        for(auto i=v.MemberBegin();i!=v.MemberEnd();++i){
            auto spec=planSpecs().find(i->name.GetString());
            if(spec==planSpecs().end()||!i->value.IsInt()||i->value.GetInt()<spec->second.minimum||i->value.GetInt()>spec->second.maximum)throw std::runtime_error("Invalid recognition threshold");
            pending[i->name.GetString()]=i->value.GetInt();
        }
        const int start=pending.count("startFrame")?pending.at("startFrame"):planSpecs().at("startFrame").original;
        const int end=pending.count("endFrame")?pending.at("endFrame"):planSpecs().at("endFrame").original;
        if(start>=end)throw std::runtime_error("Invalid recognition time window");
        values=std::move(pending);
    }
    int get(const char* key) const {auto i=values.find(key);return i==values.end()?planSpecs().at(key).original:i->second;}
};
}
'''


if __name__=='__main__':
    from pathlib import Path
    path=Path(__file__).resolve().parents[1]/'Steamhammer/Source/NNBPlanSettings.h'
    source=native_header()
    if not path.exists() or path.read_text(encoding='utf-8')!=source:path.write_text(source,encoding='utf-8')
